# Generated by Django 5.1.1 on 2024-10-17 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(blank=True, default='0000000000', max_length=10, null=True, verbose_name='Code of tag')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='TagsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags_category', models.CharField(max_length=100, verbose_name='Category of tag')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Video title')),
                ('description', models.TextField(blank=True, verbose_name='Video description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('video_file', models.FileField(unique=True, upload_to='videos/', verbose_name='Video file')),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='Image')),
                ('mask', models.ImageField(blank=True, null=True, upload_to='masks/', verbose_name='Mask')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_preparation.tag', verbose_name='Tag')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='data_preparation.tagscategory', verbose_name='Tags category'),
        ),
        migrations.CreateModel(
            name='Sequences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.CharField(max_length=255, verbose_name='Frames features')),
                ('start_time', models.IntegerField(default=0, verbose_name='Start time')),
                ('duration', models.IntegerField(default=0, verbose_name='Duration of sequence')),
                ('fps', models.IntegerField(default=1, verbose_name='FPS')),
                ('left_crop', models.IntegerField(default=0, verbose_name='Left crop')),
                ('right_crop', models.IntegerField(default=0, verbose_name='Right crop')),
                ('top_crop', models.IntegerField(default=0, verbose_name='Top crop')),
                ('bottom_crop', models.IntegerField(default=0, verbose_name='Bottom crop')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='data_preparation.video', verbose_name='Video')),
            ],
        ),
    ]
