# Generated by Django 5.1.1 on 2024-12-05 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_preparation', '0004_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procedures', to='data_preparation.procedure', verbose_name='Medical procedures'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
