# Generated by Django 5.1.1 on 2024-12-05 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_preparation', '0005_tag_procedure_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequences',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sequence_procedures', to='data_preparation.procedure', verbose_name='Medical procedures'),
        ),
    ]
