# Generated by Django 5.1.1 on 2024-11-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralNetworkVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Model Name')),
                ('version_number', models.CharField(max_length=20, verbose_name='Version Number')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('model_file', models.FileField(blank=True, null=True, upload_to='models/', verbose_name='Model File')),
                ('training_parameters', models.JSONField(blank=True, null=True, verbose_name='Training Parameters')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Model Accuracy')),
            ],
        ),
    ]
