# Generated by Django 5.1.1 on 2024-11-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettrain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuralnetworkversion',
            name='training_tags',
            field=models.JSONField(blank=True, null=True, verbose_name='Training Tags'),
        ),
    ]
