# Generated by Django 5.1.1 on 2024-10-17 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_preparation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_file', models.ImageField(upload_to='frames/', verbose_name='Frame')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Height of frame')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Width of frame')),
                ('sequences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_sequences', to='data_preparation.sequences', verbose_name='Sequences')),
            ],
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask_file', models.ImageField(upload_to='mask/', verbose_name='Mask file')),
                ('mask_color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Mask Color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('frame_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masks', to='segmentation.framesequence', verbose_name='Frame')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_class', to='data_preparation.tag', verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_sign', models.CharField(choices=[('+', 'Positive'), ('-', 'Negative')], max_length=1, verbose_name='Sign')),
                ('point_x', models.IntegerField()),
                ('point_y', models.IntegerField()),
                ('mask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='segmentation.mask', verbose_name='Mask')),
            ],
        ),
    ]
