# Generated by Django 5.1.1 on 2024-11-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=10, verbose_name='Status'),
        ),
    ]
