# Generated by Django 5.1.1 on 2024-09-25 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0002_objectclass_alter_imageupload_object_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_file', models.ImageField(upload_to='frames/', verbose_name='Кадр')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название видео')),
                ('description', models.TextField(blank=True, verbose_name='Описание видео')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='Файл видео')),
            ],
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='uploads/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='mask',
            field=models.ImageField(blank=True, null=True, upload_to='masks/', verbose_name='Mask'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='object_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='segmentation.objectclass', verbose_name='Object Class'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At'),
        ),
        migrations.AlterField(
            model_name='objectclass',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='objectclass',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask_file', models.ImageField(upload_to='masks/', verbose_name='Файл маски')),
                ('tag', models.CharField(help_text='Описание, что представляет маска', max_length=255, verbose_name='Тег маски')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('frame_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masks', to='segmentation.framesequence', verbose_name='Кадр')),
            ],
        ),
        migrations.AddField(
            model_name='framesequence',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_sequences', to='segmentation.video', verbose_name='Видео'),
        ),
    ]
