# Generated by Django 5.1.1 on 2024-09-25 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0003_framesequence_video_alter_imageupload_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_class', to='segmentation.objectclass', verbose_name='Ярлык'),
        ),
    ]
