# Generated by Django 5.1.1 on 2024-09-26 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0007_framesequence_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framesequence',
            name='features',
        ),
        migrations.RemoveField(
            model_name='framesequence',
            name='video',
        ),
        migrations.CreateModel(
            name='Sequences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.CharField(max_length=255, verbose_name='Frames features')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='segmentation.video', verbose_name='Video')),
            ],
        ),
        migrations.AddField(
            model_name='framesequence',
            name='sequences',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='frame_sequences', to='segmentation.sequences', verbose_name='Sequences'),
            preserve_default=False,
        ),
    ]
