# Generated by Django 5.1.1 on 2024-09-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0008_remove_framesequence_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequences',
            name='bottom_crop',
            field=models.IntegerField(default=0, verbose_name='Bottom crop'),
        ),
        migrations.AddField(
            model_name='sequences',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Duration of sequence'),
        ),
        migrations.AddField(
            model_name='sequences',
            name='fps',
            field=models.IntegerField(default=1, verbose_name='FPS'),
        ),
        migrations.AddField(
            model_name='sequences',
            name='left_crop',
            field=models.IntegerField(default=0, verbose_name='Left crop'),
        ),
        migrations.AddField(
            model_name='sequences',
            name='right_crop',
            field=models.IntegerField(default=0, verbose_name='Right crop'),
        ),
        migrations.AddField(
            model_name='sequences',
            name='start_time',
            field=models.IntegerField(default=0, verbose_name='Start time'),
        ),
        migrations.AddField(
            model_name='sequences',
            name='top_crop',
            field=models.IntegerField(default=0, verbose_name='Top crop'),
        ),
    ]
