# Generated by Django 5.1.1 on 2024-10-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0009_sequences_bottom_crop_sequences_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='point_x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mask',
            name='point_y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
