# Generated by Django 5.1.1 on 2024-10-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0010_mask_point_x_mask_point_y_alter_mask_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='framesequence',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Height of frame'),
        ),
        migrations.AddField(
            model_name='framesequence',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Width of frame'),
        ),
    ]
