# Generated by Django 5.1.1 on 2024-10-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0012_alter_mask_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mask',
            name='point_x',
        ),
        migrations.RemoveField(
            model_name='mask',
            name='point_y',
        ),
        migrations.AddField(
            model_name='mask',
            name='mask_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Mask Color'),
        ),
        migrations.AlterField(
            model_name='mask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_sign', models.CharField(choices=[('+', 'Positive'), ('-', 'Negative')], max_length=1, verbose_name='Sign')),
                ('point_x', models.IntegerField()),
                ('point_y', models.IntegerField()),
                ('mask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='segmentation.mask', verbose_name='Mask')),
            ],
        ),
    ]
