# Generated by Django 5.1.1 on 2024-10-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0013_remove_mask_point_x_remove_mask_point_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='mask_file',
            field=models.ImageField(upload_to='mask/', verbose_name='Mask file'),
        ),
    ]
