# Generated by Django 5.1.1 on 2024-10-14 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0014_alter_mask_mask_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObjectClass',
            new_name='Tag',
        ),
    ]
