# Generated by Django 5.1.1 on 2024-10-14 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0017_alter_tag_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='segmentation.tagscategory', verbose_name='Tags category'),
            preserve_default=False,
        ),
    ]
